#-spring.datasource.url=jdbc:mysql://e-commerce.cfmx05xtq7u5.us-east-2.rds.amazonaws.com:3306/e-commerce
#spring.datasource.username=admin
#spring.datasource.password=Java1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce
    username: root
    password: Feb@2011
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 8088