
#spring:
#  datasource:
#    url: jdbc:mysql://e-commerce.cfmx05xtq7u5.us-east-2.rds.amazonaws.com:3306/e-commerce
#    username: admin
#    password: Java1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true