#-spring.datasource.url=jdbc:mysql://e-commerce.cfmx05xtq7u5.us-east-2.rds.amazonaws.com:3306/e-commerce
#spring.datasource.username=admin
#spring.datasource.password=Java1234
server:
  port: 8008
spring:
  datasource:
    username: sa
    url: jdbc:h2:./app.mv

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  h2:
    console:
      enabled: true










