spring:
  datasource:

    url: jdbc:h2:mem:appdb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  h2:
    console:
      enabled: true

server:
  port: 8081


